// <auto-generated />
using InförCheckpoint6;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InförCheckpoint6.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InförCheckpoint6.SkidåkTyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SkidåkareId");

                    b.Property<string>("typ");

                    b.HasKey("Id");

                    b.HasIndex("SkidåkareId");

                    b.ToTable("SkidåkTyps");
                });

            modelBuilder.Entity("InförCheckpoint6.Skidåkare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Efternamn");

                    b.Property<string>("Förnamn");

                    b.HasKey("Id");

                    b.ToTable("Skidåkares");
                });

            modelBuilder.Entity("InförCheckpoint6.SkidåkTyp", b =>
                {
                    b.HasOne("InförCheckpoint6.Skidåkare", "Skidåkare")
                        .WithMany("SkidåkTyps")
                        .HasForeignKey("SkidåkareId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
